### ISSUE TITLE
:verifyRelease - No signature of method - After updating from 1.18.8 to 1.18.9

### ISSUE THREAD

**Issue by greenjoe** [allegro/axion-release-plugin#827] opened 2024-10-01 09:16 UTC
Hello, in one of our libraries the "release" step fails after updating the plugin from 1.18.8 to 1.18.9. The error message is:
```

> Task :verifyRelease FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':verifyRelease'.
> Failed to calculate the value of task ':verifyRelease' property 'snapshotDependencies'.
   > No signature of method: java.lang.String.positive() is applicable for argument types: () values: []
     Possible solutions: notify(), size(), tokenize()

```
The update works in our other gradle projects, but fails in one multi-module gradle project. I'm not sure if this is some kind of bug in the plugin or possibly we have an incorrect configuration. Could you please give me any hints?

**Comment by bgalek** [comment] 2024-10-01 10:53
Hi, that's really strange, take a look:
https://github.com/allegro/axion-release-plugin/compare/v1.18.8...v1.18.9

The only thing released in 1.18.9 was the fix for concurrent map modification and `runtimeOnly("net.java.dev.jna:jna-platform:5.15.0")`

Could you check if forcing a downgrade of jna helps?

**Comment by greenjoe** [comment] 2024-10-01 11:57
It doesn't seem to help, I've tried
```
buildscript {
    configurations.all {
        resolutionStrategy {
            force 'net.java.dev.jna:jna-platform:5.14.0' // desired older version
        }
    }
}
``` 
and then 
`./gradlew buildEnvironment` 
to verify that the version was downgraded. But I'm still getting an error. 


The concurrent map modification changes you mentioned are touching "SnapshotDependenciesChecker" and the error mentions "snapshotDependencies" so I thought perhaps it is related? Adding `--stacktrace` I'm getting 

```
Caused by: groovy.lang.MissingMethodException: No signature of method: java.lang.String.positive() is applicable for argument types: () values: []
Possible solutions: notify(), tokenize(), size()
        at pl.allegro.tech.build.axion.release.domain.SnapshotDependenciesChecker.snapshotVersions(SnapshotDependenciesChecker.groovy:20)
        at pl.allegro.tech.build.axion.release.domain.SnapshotDependenciesChecker$snapshotVersions.call(Unknown Source)
```

**Comment by hetzijzo** [comment] 2024-10-01 13:10
We have exact the same issue with the axion-release-plugin and traced it down to the 1.18.9 version.

**Comment by bgalek** [comment] 2024-10-01 13:18
@hetzijzo or @greenjoe could you share your repo link? I'll could take a look

**Comment by greenjoe** [comment] 2024-10-01 15:31
Hello, I couldn't share the link to the actual repository I'm working on but I've found a way to create an almost empty gradle project from scratch that seems to replicate the issue 
https://github.com/greenjoe/axion-test 

`./gradlew release`

**Comment by bgalek** [comment] 2024-10-01 20:28
@greenjoe, thx, I've confirmed that this bug was introduced in https://github.com/allegro/axion-release-plugin/pull/819 I'll try to fix it ASAP

**Comment by bgalek** [comment] 2024-10-01 21:18
It seems to be working on the project you provided, and all other tests are passing, so I hope it will resolve the issue

**Comment by bgalek** [comment] 2024-10-01 21:28
v1.18.10 was just released, I hope it will work as expected now

**Comment by ksiczek** [comment] 2024-10-02 06:19
With v1.18.10 we're getting 

```
Execution failed for task ':verifyRelease'.
> The project uses snapshot versions - can't release. Snapshots found: [***.**.*:commons-service:3.2.300-SNAPSHOT, ***.**.*:commons-test:3.2.300-SNAPSHOT, ***.**.*:commons-rest:3.2.300-SNAPSHOT, ***.**.*:commons-processor:3.2.300-SNAPSHOT, ***.**.*:commons-kafka:3.2.300-SNAPSHOT, ***.**.*:commons-security:3.2.300-SNAPSHOT]
```

which seems similar to the [330](https://github.com/allegro/axion-release-plugin/issues/330). Is it a new issue/a regression?

**Comment by bgalek** [comment] 2024-10-02 06:36
@ksiczek could you share your Gradle project layout? I assume your Gradle module referenced in another module is detected as snapshot?

**Comment by ksiczek** [comment] 2024-10-02 06:57
Sure @bgalek. This is a multi-module project with the directory structure as follows:
```
commons-java
├── CODEOWNERS
├── README.md
├── build.gradle
├── commons-bom
├── commons-kafka
├── commons-processor
├── commons-rest
├── commons-security
├── commons-service
├── commons-test
├── gradle
├── gradle.properties
├── gradlew
├── libs.versions.toml
├── renovate.json
└── settings.gradle
```
We release everything as a single version. 

/build.gradle

```
subprojects {
    apply plugin: 'maven-publish'
    project.version = scmVersion.version
    publishing {
        repositories {
...
        }
    }
```
The sub-projects are not related to the axion or release. I jumped in here because we also faced the issue with `1.18.9` despite having had a smooth release for months. Now there is the `1.18.10` which traded one problem for the other :)

**Comment by bgalek** [comment] 2024-10-02 06:58
Thanks! I'll look into this today, I hope to resolve it so you'll get back on track!

**Comment by greenjoe** [comment] 2024-10-02 08:12
I would like to confirm that 1.18.10 works correctly in my repository. Thank you for fixing it so quickly :)

**Comment by marcopacurariu3** [comment] 2024-10-02 13:44
@bgalek, in the project that I'm working on, I have the same issue as mentioned by @ksiczek, please let me know when there's a fix for it, it appeared indeed in version 1.18.10

**Comment by bgalek** [comment] 2024-10-02 23:00
@hetzijzo did the last release resolved your problem too?

**Comment by bgalek** [comment] 2024-10-02 23:01
@marcopacurariu3 @ksiczek I need more information, to reproduce the issue.

Could you prepare a repository like @greenjoe did or a PR with failing test?
In case of https://github.com/greenjoe/axion-test it works the same as the previous versions (v1.18.8 and v1.18.10 works the same - the problem was only with v1.18.9).

**Comment by danielnicinski** [comment] 2024-10-03 12:48
@bgalek I prepared a repository which reflects the configuration we have with @ksiczek 
https://github.com/danielnicinski/axion-demo-1

**Comment by marcindabrowski** [comment] 2024-10-04 08:09
@bgalek I used `1.18.11` in my project with multiple modules and got error:

```
> Task :verifyRelease FAILED
Looking for uncommitted changes.. 
Checking if branch is ahead of remote.. 
Checking for snapshot versions.. FAILED
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':verifyRelease'.
> The project uses snapshot versions - can't release. Snapshots found: [com.example:example-core:1.1.3-SNAPSHOT, com.example:example-json:1.1.3-SNAPSHOT]
```

The project has 11 modules, but snapshots where found in 5 of them.
It worked when I downgraded plugin to `1.18.8`.

Release was performed by GitHub Action.

**Comment by bgalek** [comment] 2024-10-04 09:37
@marcindabrowski I assume you have necessary tags in your repository (for each module)
example-core-1.1.3
and example-json:1.1.3
in place? if not, those are snapshots

**Comment by bgalek** [comment] 2024-10-04 09:39
@danielnicinski I don't see per module tag configuration, so how axion-release-plugin would know if it's a module snapshot or not?

**Comment by bgalek** [comment] 2024-10-04 09:53
ok, i think i see the bug, thanks for your examples, I'll need to prepare a test in repo for that

**Comment by bgalek** [comment] 2024-10-04 10:07
this should do the trick: https://github.com/allegro/axion-release-plugin/pull/831/files
I'll test this snapshot in provided repositories

**Comment by marcindabrowski** [comment] 2024-10-04 11:05
> @marcindabrowski I assume you have one version for every submodule?

Yes, and I have one tag for whole repository.

**Comment by bgalek** [comment] 2024-10-04 15:15
@marcindabrowski @danielnicinski @ksiczek I'll release a fix today, please get back to me if this helped

**Comment by marcindabrowski** [comment] 2024-10-14 08:28
@bgalek version 1.18.12 is working with my projects.
Thanks!

**Comment by danielnicinski** [comment] 2024-10-14 09:00
> @marcindabrowski @danielnicinski @ksiczek I'll release a fix today, please get back to me if this helped - provided tests reposities are working from snapshot

I confirm it fixed the issue we had. Thanks

**Comment by ksiczek** [comment] 2024-10-14 09:02
That works great for us too. It was blazing fast, thanks a ton.

**Closed** 2024-10-14 18:01 UTC
