### ISSUE TITLE
 java.lang.StackOverflowError when project in is a sub folder of a repository

### ISSUE THREAD

**Issue by baptistemesta** [allegro/axion-release-plugin#194] opened 2017-07-21 12:46 UTC
I came across a StackOberflowError issue while trying to apply the plugin on a project that is under a subfolder.

here is the error:
```
gw cV

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred evaluating root project 'my-project'.
> java.lang.StackOverflowError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 1s
```

the stack is like this:
```

```

I created a repository to reproduce it:
clone this repository: https://github.com/baptistemesta/reproduce-axion-release-issue
checkout the branch `feat/test1`
go in the subfolder `sub/my-project/test2/`
run `gradlew cV`

**Comment by adamdubiel** [comment] 2017-07-26 19:45
Thanks for reporting! However im on vacation, so i will get to it once i
come back.

**Comment by adamdubiel** [comment] 2017-07-31 16:31
I did as you described:

```
$ git clone git@github.com:baptistemesta/reproduce-axion-release-issue.git
$ cd reproduce-axion-release-issue/
$ git checkout origin/feat/test1

HEAD is now at e164248... test

$ cd sub/my-project/test2/
$ ./gradlew cV -s

> Task :currentVersion

Project version: 0.1.0-SNAPSHOT
```

and error did not occur. Did i miss any step or you are doing something differently?

**Comment by adamdubiel** [comment] 2017-10-07 08:41
Just to be sure, i tried it once again and once again was not able to reproduce. I will close this issue for now, but please feel free to reopen if you have more details or i messed sth.

**Closed by adamdubiel** 2017-10-07 08:41 UTC

**Comment by baptistemesta** [comment] 2017-10-07 10:12
sorry for not giving more feedbacks (+ I forgot the stacktrace! )
I think it might be environmental...

Here is the full stacktrace:
```
* What went wrong:
A problem occurred evaluating root project 'my-project'.
> java.lang.StackOverflowError (no error message)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'my-project'.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:92)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:187)
        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:192)
        at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:61)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:58)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:63)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$100(LifecycleProjectEvaluator.java:33)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$ConfigureProject.run(LifecycleProjectEvaluator.java:103)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:49)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:654)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:132)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:60)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
        at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuild.run(DefaultGradleLauncher.java:195)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:157)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:44)
        at org.gradle.initialization.DefaultGradleLauncher$1.run(DefaultGradleLauncher.java:122)
        at org.gradle.internal.work.DefaultWorkerLeaseService$2.execute(DefaultWorkerLeaseService.java:124)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:116)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:99)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$1.run(RunAsBuildOperationBuildActionRunner.java:43)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:44)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:51)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:32)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:64)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:42)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:50)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.StackOverflowError
        at org.eclipse.jgit.util.FileUtils.exists(FileUtils.java:573)
        at org.eclipse.jgit.util.FS.exists(FS.java:645)
        at org.eclipse.jgit.internal.storage.file.FileSnapshot$1.isModified(FileSnapshot.java:90)
        at org.eclipse.jgit.internal.storage.file.RefDirectory.getPackedRefs(RefDirectory.java:767)
        at org.eclipse.jgit.internal.storage.file.RefDirectory.getRef(RefDirectory.java:290)
        at org.eclipse.jgit.lib.Repository.getRef(Repository.java:912)
        at org.eclipse.jgit.lib.Repository$getRef$0.call(Unknown Source)
        at org.ajoberstar.grgit.util.JGitUtil.resolveBranch(JGitUtil.groovy:200)
        at org.ajoberstar.grgit.util.JGitUtil$resolveBranch$3.callStatic(Unknown Source)
        at org.ajoberstar.grgit.util.JGitUtil.resolveBranch(JGitUtil.groovy:221)
        at org.ajoberstar.grgit.util.JGitUtil$resolveBranch$2.callStatic(Unknown Source)
        at org.ajoberstar.grgit.util.JGitUtil.resolveBranch(JGitUtil.groovy:201)
        at org.ajoberstar.grgit.util.JGitUtil$resolveBranch$3.callStatic(Unknown Source)
        at org.ajoberstar.grgit.util.JGitUtil.resolveBranch(JGitUtil.groovy:221)
        at org.ajoberstar.grgit.util.JGitUtil$resolveBranch$2.callStatic(Unknown Source)
        at org.ajoberstar.grgit.util.JGitUtil.resolveBranch(JGitUtil.groovy:201)
        at org.ajoberstar.grgit.util.JGitUtil$resolveBranch$3.callStatic(Unknown Source)
      [...]
        at org.ajoberstar.grgit.util.JGitUtil.resolveBranch(JGitUtil.groovy:201)
        at org.ajoberstar.grgit.util.JGitUtil$resolveBranch$3.callStatic(Unknown Source)
        at org.ajoberstar.grgit.util.JGitUtil.resolveBranch(JGitUtil.groovy:221)
        at org.ajoberstar.grgit.util.JGitUtil$resolveBranch$2.callStatic(Unknown Source)
        at org.ajoberstar.grgit.util.JGitUtil.resolveBranch(JGitUtil.groovy:201)
        at org.ajoberstar.grgit.util.JGitUtil$resolveBranch$3.callStatic(Unknown Source)


BUILD FAILED in 1s
```

And the environment:
```
------------------------------------------------------------
Gradle 4.0
------------------------------------------------------------

Build time:   2017-06-14 15:11:08 UTC
Revision:     316546a5fcb4e2dfe1d6aa0b73a4e09e8cecb5a5

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_65 (Oracle Corporation 25.65-b01)
OS:           Mac OS X 10.12.6 x86_64
```

I'm not blocked by this bug anymore and it might be environmental so I'm not sure If its worth spending time on it. Maybe if someone else come across that bug again he can reopen the issue.

Thank you for your time!

**Comment by adamdubiel** [comment] 2017-10-07 10:31
Hmm looks like a bug somewhere deep in JGit. I tested your repo on Mac OS as well, same version (`Mac OS X 10.12.6 x86_64`) and got it working flawlessly.. i would really like to help, but without being able to reproduce and stack pointing to JGit i don't have a clue how to approach it.

However if you can reproduce this problem on your env, maybe try using the newest version (1.8.1), i bumped version of JGit in one of the commits (https://github.com/allegro/axion-release-plugin/commit/89ff1941e78b4e7810169a2ed1473ad673a00bfa).

**Comment by tbouffard** [comment] 2017-10-09 08:45
Just for the record, I had the same issue on Windows OS when working with @baptistemesta on another repo.
I cannot reproduce the problem anymore with the public repo.

**Comment by adamdubiel** [comment] 2017-10-09 08:57
Let me know if something like this happens on newest version with fresh JGit - i hope there was some fix for this :)
