### ISSUE TITLE
Modifying files with pre/post during CI build

### ISSUE THREAD

**Issue by imavroukakis** [allegro/axion-release-plugin#90] opened 2015-07-24 10:08 UTC
I've hit a wall with regards to auto-incrementing certain version numbers during release. It's probably a conceptual issue but it might be worth running it past you.
I have the following hooks
```
 hooks {
        pre 'fileUpdate', [file   : 'src/main/scripts/upstart/service.conf',
                           pattern: { v, p -> /module_version="$v-SNAPSHOT"/ }, replacement: { v, p -> "module_version=\"$v\"" }]
        pre 'commit'
        post 'fileUpdate', [file   : 'gradle.properties',
                           pattern: { v, p -> /rpmRelease=$project.rpmRelease/ }, replacement: { v, p -> "rpmRelease=${project.rpmRelease.toInteger() + 1}" }]
    }
```
What I'm trying to do is: 
* Amend the version in `service.conf`
* Build
* Release and publish
* Amend the `rpmRelease` number by 1, to start the next iteration process (i.e. the next scm checkout for the CI continuous build should be a SNAPSHOT)

Unfortunately, I can't figure out a way for axion to do another commit/push to GitHub as part of the `post fileUpdate` action. Is that even possible?

Thanks!

**Comment by imavroukakis** [comment] 2015-07-24 10:35
After a little thought, I've arrived at this

```

task doRpmBuildAfterRelease(type: GradleBuild){
    tasks = ['buildRpm']
}

scmVersion {

    nextVersion {
        suffix = 'devel'
        separator = '-'
    }

    tag {
        prefix = rootProject.name
        initialVersion = { config, position -> '1.0.0' }
    }

    hooks {
        pre 'fileUpdate', [file   : 'src/main/scripts/upstart/service.conf',
                           pattern: { v, p -> /module_version="$v-SNAPSHOT"/ }, replacement: { v, p -> "module_version=\"$v\"" }]
        pre 'commit'
        pre {context ->
            doRpmBuildAfterRelease.execute()
        }
        post 'fileUpdate', [file   : 'gradle.properties',
                           pattern: { v, p -> /rpmRelease=$project.rpmRelease/ }, replacement: { v, p -> "rpmRelease=${project.rpmRelease.toInteger() + 1}" }]
        pre {context ->
            context.commit(['gradle.properties'], 'Next development iteration')
        }
    }
}

project.version = scmVersion.version
```
Now what happens is as follows

./gradlew release -Prelease.localOnly

* Updates `service.conf`
* Commits and releases
* Builds RPM
* Updates `gradle.properties`
* Commits the change

Now the question becomes, does the `commit` action also push to the remote repo?

**Comment by imavroukakis** [comment] 2015-07-24 11:07
To recap, the main issue how to 
* modify files before release
* release
* build artifact
* publish
* modify files after publish
* commit changes to remote

**Comment by imavroukakis** [comment] 2015-07-24 11:31
Ok nearly there

```
task doRpmBuildAndPublishAfterRelease(type: GradleBuild) {
    tasks = ['clean', 'buildRpm','publish']
}

scmVersion {

    nextVersion {
        suffix = 'devel'
        separator = '-'
    }

    tag {
        prefix = rootProject.name
        initialVersion = { config, position -> '1.0.0' }
    }

    hooks {
        pre 'fileUpdate', [file   : 'src/main/scripts/upstart/cache-service.conf',
                           pattern: { v, p -> /module_version="$v-SNAPSHOT"/ }, replacement: { v, p -> "module_version=\"$v\"" }]
        pre 'commit'
        post { context ->
            doRpmBuildAndPublishAfterRelease.execute()
        }
        post 'fileUpdate', [file   : 'gradle.properties',
                            pattern: { v, p -> /rpmRelease=$project.rpmRelease/ }, replacement: { v, p -> "rpmRelease=${project.rpmRelease.toInteger() + 1}" }]
        post { context ->
            context.commit(['gradle.properties'], "Next development iteration")
        }
    }
}

project.version = scmVersion.version
```
So, back to my previous question, will the last hook's commit also push to remote ? :smile:

**Comment by adamdubiel** [comment] 2015-07-26 20:30
It took me while to go through all the iterations, but i think i get the problem :)

So, as you might have noticed in documentation, axion-release is for release only, it does not manage publishing. One reason is, most gradle plugins do not like change of `project.version` in runtime. But i guess this is not the issue here, as you managed to do some publishing in `post` phase. Mind though, that there is no transaction and no rollback here, so if post fails, build will fail but release is already there.

Back to your problem, the `pre` and `post` phases mean:

* `pre` - before release, as in before creating tag and pushing to remote
* `post` - after release, as in after creating tag and pushing to remote

So anything you do in `post` phase, it does not end in remote. You would have to create new `push` action and plug it in manually. This is actually quite simple and i might add it to predefined actions set per your request, but i would like to get the "conceptual issues" cleared first :)

**Comment by imavroukakis** [comment] 2015-07-27 10:46
Ok that's awesome :) how do I create a push action?

**Comment by adamdubiel** [comment] 2015-07-27 12:47
It's all here :) http://axion-release-plugin.readthedocs.org/en/latest/configuration/hooks.html#custom-action let me know if you need any help

**Comment by imavroukakis** [comment] 2015-07-27 12:54
You mean what I'm doing already?

```
post { context ->
            context.commit(['gradle.properties'], "Next development iteration")
        }
```

**Comment by adamdubiel** [comment] 2015-07-27 13:12
Ah, sorry for misleading you, repository is not exposed here. I need to add this operation to accessible operations, so you could do sth as simple as:

```
post 'push'
```

**Comment by imavroukakis** [comment] 2015-07-27 13:14
why not just add it as an action to `context` ?

**Comment by imavroukakis** [comment] 2015-07-27 13:39
Hmm I realised my plan might not work exactly as I wished for
```
hooks {
        pre 'fileUpdate', [file   : "src/main/scripts/upstart/${rootProject.name}.conf",
                           pattern: { v, p -> /module_version="$v-SNAPSHOT"/ }, replacement: { v, p -> "module_version=\"$v\"" }]
        pre 'commit'
        post { context ->
            doRpmBuildAndPublishAfterRelease.execute()
        }
        post 'fileUpdate', [file   : 'gradle.properties',
                            pattern: { v, p -> /rpmRelease=$project.rpmRelease/ }, replacement: { v, p -> "rpmRelease=${project.rpmRelease.toInteger() + 1}" }]
        post { context ->
            context.commit(['gradle.properties'], "Advance RPM release")
        } <---This works fine, RPM number advances
        post 'fileUpdate', [file   : "src/main/scripts/upstart/${rootProject.name}.conf",
                            pattern: { v, p -> /module_version="$v"/ }, replacement: { v, p -> "module_version=\"$v\"" }] <== This however doesn't, version is still 1.0.0. I expected it to be 1.0.1-SNAPSHOT
        post { context ->
            context.commit(["src/main/scripts/upstart/${rootProject.name}.conf"], "Next development iteration")
        }
    }
```

**Comment by adamdubiel** [comment] 2015-07-27 14:25
This is the issue i wanted to highlight in my first comment - Gradle does not like changing version in runtime, thus axion does not do it at all. So if you need to have access to version after release, you need to run gradle once again.

This is exactly the reason why normal `publish` task can't be used with `release` in one run.

**Comment by imavroukakis** [comment] 2015-07-27 14:31
I just realised the same thing..So I can only see two ways to get around this. Either do some really  ugly sed scripting on the CI server as a post release/publish build action, or find some way to execute post hooks after `release`. It would be really cool if one could do `gradle release:post` or something similar :-)

**Comment by imavroukakis** [comment] 2015-07-27 15:22
Actually I think I've got this backwards. We don't really need to modify `project.version` but what would be useful is if there was someway to "get" the next release or "snapshot" version during the `post` hook phase. This way, we don't violate the gradle requirements.

**Comment by adamdubiel** [comment] 2015-07-27 15:57
Hmm.. i would have to take a closer look at current implementation, but i think its doable.

**Comment by imavroukakis** [comment] 2015-07-27 16:22
Excellent. That means that `post` hooks become very powerful when it comes to applying version changes to files.

**Comment by imavroukakis** [comment] 2015-07-27 16:52
Also, adding `post 'push'` makes it the complete package.

**Comment by adamdubiel** [comment] 2015-07-28 06:43
Adding `push` was no big deal, but there is a problem with exposing bleeding-edge-version to actions. Take your flow for example:

* release
* post action: commit
* post action: do some other stuff on files
* post action: commit
* post action: push

I can't simply read version after release and pass it on - that's easy, version will be `1.0.0` and its already available in context. Since i don't know what are your actions, i need to read version before every post action, as they can change what is perceived as current version:

* release
* evaluate version: 1.0.0
* post action: commit
* evaluate version: 1.0.1-SNAPSHOT
* ...

I can't simply _guess_ what next version is, since there are a lot of possibilities to customize version calculation and i would not want to have parallel flow, next to the one that reads stuff from git. I still wonder if it's necessary.. but i will try to get this straight.

**Comment by imavroukakis** [comment] 2015-07-28 10:44
Actually I don't think that's going to be much of an issue. From what I understand from the code, there are pre-defined way to increment your code based on semver. If all you are using is that, then we can simply return the next version, based on semver semantics; but if you are using a custom versioning strategy, then simply do not support picking up the next version.

**Comment by adamdubiel** [comment] 2015-07-28 11:19
Yeah, but this is building parallel versioning - the "full" path and "simple" semver path :)

**Comment by imavroukakis** [comment] 2015-07-28 12:16
Hmm I don't think I understand the difference between "full" and "simple" then. Here's how I thought it would work:
Say we are at `1.0.1-SNAPSHOT`
* Pre hook - Modify version in files to `1.0.1`
* Commit
* Release
    * now we are at `1.0.1`
* Post hook - Build artifacts and publish
* Post hook - modify files
    * We're still at `1.0.1-SNAPSHOT`. So at this point I would ideally call method(s) that returns either the next `patch` version or the next `minor` version, i.e. `1.0.2-SNAPSHOT` or `1.1.0-SNAPSHOT`
* Commit and push to remote

So, if you can figure out the next version as part of the `pre fileUpdate` hook, can we not do the same as part of the `post fileUpdate` hook?

**Comment by adamdubiel** [comment] 2015-08-15 21:31
For now i have added `push` action, as things are not as easy as they might seem.

**Comment by imavroukakis** [comment] 2015-08-16 09:42
great looking forward to it.

**Comment by imavroukakis** [comment] 2015-08-17 16:08
I saw the commit merged into mainline, when can I start using 1.3.1 ? :smile:

**Comment by adamdubiel** [comment] 2015-08-17 20:23
Just released it :) enjoy and let me know if it helped

**Comment by imavroukakis** [comment] 2015-08-18 09:18
Hmm I'm getting this error

```
> No signature of method: pl.allegro.tech.build.axion.release.domain.hooks.HooksConfig.post() is applicable for argument types: (java.lang.String) values: [push]
  Possible solutions: post(groovy.lang.Closure), post(java.lang.String, groovy.lang.Closure), post(java.lang.String, java.util.Map), pre(java.lang.String), wait(), wait(long)
```
all I did was add `post 'push'` to `hooks { }`

**Comment by adamdubiel** [comment] 2015-08-18 09:31
Can you add `post 'push', []` ? I tested it with `pre` and there might be this slight difference.

**Comment by imavroukakis** [comment] 2015-08-18 09:35
Sorry, similar error :crying_cat_face: 
```
> No signature of method: pl.allegro.tech.build.axion.release.domain.hooks.HooksConfig.post() is applicable for argument types: (java.lang.String, java.util.ArrayList) values: [push, []]
```

Here's my entire config

```
scmVersion {

    ignoreUncommittedChanges = false

    nextVersion {
        suffix = 'devel'
        separator = '-'
    }

    tag {
        prefix = rootProject.name
        initialVersion = { config, position -> '1.0.0' }
    }

    hooks {
        pre 'fileUpdate', [file   : "src/main/scripts/upstart/${rootProject.name}.conf",
                           pattern: { v, p -> /module_version="$v-SNAPSHOT"/ }, replacement: { v, p -> "module_version=\"$v\"" }]
        pre 'commit'
        post { context ->
            doRpmBuildAndPublishAfterRelease.execute()
        }
        post 'fileUpdate', [file   : 'gradle.properties',
                            pattern: { v, p -> /rpmRelease=$project.rpmRelease/ }, replacement: { v, p -> "rpmRelease=${project.rpmRelease.toInteger() + 1}" }]
        post { context ->
            context.commit(['gradle.properties'], "Advance RPM release")
        }
        post 'fileUpdate', [file   : "src/main/scripts/upstart/${rootProject.name}.conf",
                            pattern: { v, p -> /module_version="$v"/ }, replacement: { v, p -> "module_version=\"$v\"" }]
        post { context ->
            context.commit(["src/main/scripts/upstart/${rootProject.name}.conf"], "Next development iteration")
        }
        post 'push', []
    }
}
```

**Comment by adamdubiel** [comment] 2015-08-18 09:47
Ah, sorry, i mad a typo :) I meant `post 'push' [:]` (to make it Map, not ArrayList)

**Comment by imavroukakis** [comment] 2015-08-18 09:52
No luck :(
`> class pl.allegro.tech.build.axion.release.domain.hooks.PushHookAction$Factory does not construct release hooks from Map`

However, this worked!
` post 'push', {}`

The only issue I can see is that even though I used `-Prelease.localOnly` it still pushed the changes. I reckon `push` should be ignored if `-Prelease.localOnly` is set.

**Comment by adamdubiel** [comment] 2015-08-18 10:41
Okay, i will take a closer look at both of those issues. Too bad i couldn't send you snapshot to test before releasing.

**Comment by imavroukakis** [comment] 2015-08-18 10:48
Thank you, I'm at your disposal :+1: With regards to the other requirement, can I now retrieve the "next" version somehow, as part of the `post` phase?

**Comment by adamdubiel** [comment] 2015-08-18 15:29
Okay, so `localOnly` - there was unnecessary code repetition, i merged it all into single place, now it will work just as expected. I also added possibility to define `post 'push'` without any maps or closures.

The other requirement has not been met yet, but actually after reading your comment i have an idea about how it could be implemented easily. So stay tuned :)

**Comment by imavroukakis** [comment] 2015-08-18 15:36
Great thank you! In the meantime I've come across a particularly bizarre issue.
Say I am on version 1.0.0-SNAPSHOT. I call `gradlew release` and as part of my pre hooks, I update a version string in a file. The hook is this

```
        pre 'fileUpdate', [file   : "src/main/scripts/upstart/${rootProject.name}.conf",
                           pattern: { v, p -> /module_version="$v-SNAPSHOT"/ }, replacement: { v, p -> "module_version=\"$v\"" }]
```

On the very first release, this works fine, i.e. `1.0.0-SNAPSHOT` becomes `1.0.0`. 

Now I edit the same file, and update `module_version` to `1.0.1-SNAPSHOT`. I commit the file and run the release again, but this time for some reason it's trying to replace the previous version, as you can see in the debug logs.

```
16:31:09.996 [INFO] [org.gradle.api.Project] Replacing pattern "module_version="1.0.0-SNAPSHOT"" with "module_version="1.0.1"" in src/main/scripts/upstart/cache-service.conf
16:31:10.000 [QUIET] [org.gradle.api.Project] Creating tag: cache-service-1.0.1
```

Really confused!

**Comment by adamdubiel** [comment] 2015-08-18 15:42
Okay, so how about adding `forceReloadVersion()` method to context? It would return version as seen by git, but it would also take some time to execute (like it has to read it from Git).

* pre -> previousVersion: 0.1.0-SNAPSHOT, currentVersion: 0.1.0, forceReloadVersion(): 0.1.0-SNAPSHOT
* .. release ..
* post -> previousVersion: 0.1.0-SNAPSHOT, currentVersion: 0.1.0, forceReloadVersion(): 0.1.0
* post -> commit
* post -> previousVersion: 0.1.0-SNAPSHOT, currentVersion: 0.1.0, forceReloadVersion(): 0.1.1-SNAPSHOT

It might be bit counterintuitive, but that's because of field naming.

* previousVersion should be beforeReleaseVersion
* currentVersion should be releaseVersion
* forceReloadVersion() should be currentVersion

Actually i might deprecate current fields and add better named ones.

**Comment by adamdubiel** [comment] 2015-08-18 15:43
Can you show the commands you are running? Like:

```
# gradle release
# gradle cV
# git add . && git commit
# gradle cV
# gradle release
# gradle cV
```

so i can trace what version `axion` sees in between?

**Comment by imavroukakis** [comment] 2015-08-18 15:50
`forceReloadVersion()`: That sounds great. Alternatively it could be made as a simple post hook action, so it can be interleaved only where required? i.e. `post 'forceReloadVersion'`

wrt to my issue
`gradlew cV`
`gradlew --debug release -Prelease.localOnly`
edit the module_version to  `-SNAPSHOT`
`git commit -a  -m"test"`
`gradlew --debug release -Prelease.localOnly` <--tries to match against previous version 
`gradlew cV`

**Comment by adamdubiel** [comment] 2015-08-18 17:02
I meant - show me the output as well :) What are the versions step by step.

**Comment by imavroukakis** [comment] 2015-08-18 18:21
Sorry took the instructions too literally. Here we go

```
#./gradlew cV
Project version: 1.0.0-SNAPSHOT
```
`env module_version="1.0.0-SNAPSHOT"`
```
#./gradlew --debug release -Prelease.localOnly
19:15:12.790 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':release'.
19:15:12.848 [INFO] [org.gradle.api.Project] Replacing pattern "module_version="1.0.0-SNAPSHOT"" with "module_version="1.0.0"" in src/main/scripts/upstart/cache-service.conf
19:15:12.954 [QUIET] [org.gradle.api.Project] Creating tag: cache-service-1.0.0
19:15:13.028 [QUIET] [org.gradle.api.Project] Changes made to local repository only
```
`env module_version="1.0.0"`

```
#./gradlew cV
Project version: 1.0.1-SNAPSHOT
```

Change `env module_version="1.0.0"` to 1.0.1-SNAPSHOT and commit
```
git commit -a  -m"test"
[master 03a09ec] test
 1 file changed, 1 insertion(+), 1 deletion(-)
```
```
#./gradlew cV
Project version: 1.0.1-SNAPSHOT
```

```
#./gradlew --debug release -Prelease.localOnly
19:19:56.900 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':release'.
19:19:56.964 [INFO] [org.gradle.api.Project] Replacing pattern "module_version="1.0.0-SNAPSHOT"" with "module_version="1.0.1"" in src/main/scripts/upstart/cache-service.conf
19:19:57.043 [QUIET] [org.gradle.api.Project] Creating tag: cache-service-1.0.1
19:19:57.094 [QUIET] [org.gradle.api.Project] Changes made to local repository only
```

```
#./gradlew cV
:currentVersion
Project version: 1.0.2-SNAPSHOT
```

**Comment by adamdubiel** [comment] 2015-08-18 20:28
Can you edit the last comment and show also the relevant bits of `git tag` durign different stages?

**Comment by imavroukakis** [comment] 2015-08-18 21:30
done

**Comment by adamdubiel** [comment] 2015-08-19 20:50
Okay, so it took me a while, but now i know what's behind this behavior.

First of all you set initial version to `1.0.0`. This is important here, as initial version means there is nothing behind this version.

On the first run you get `1.0.0-SNAPSHOT -> 1.0.0` substitution.
On the second run you get `1.0.0-SNAPSHOT -> 1.0.1` substitution.

On the first run there is no previous version (normally would be something like 0.9.0), so the `v` in `pattern` closure is set to `1.0.0`.
On the second run there already is a previous version, which is 1.0.0, so the `v` in `pattern` closure is once again set to `1.0.0`.

If you would run it once again, you would see something like: `1.0.1-SNAPSHOT -> 1.0.2` substitution, because now previous version is `1.0.1` and current is `1.0.2`.

**Comment by imavroukakis** [comment] 2015-08-20 08:17
Ok I follow. This is fine when releasing for production, however the same script is useable across several environments, including ones considered ok to receive a SNAPSHOT. So  `fileUpdate` becomes good only for

**Comment by adamdubiel** [comment] 2015-08-20 09:14
Yes, it was intended primarily to update versions release by release. I think if i add this `forceReadCurrentVersion` it will solve both your problems.

**Comment by imavroukakis** [comment] 2015-08-20 09:47
Great, can't wait to try it out!

**Comment by adamdubiel** [comment] 2015-08-20 20:12
Okay, so i added possibility to read fresh version, it's now in develop branch. Usage sample:

```
hooks {
    post 'fileUpdate', [file: 'README.md', pattern: {v, p -> /(version:) $v/}, replacement: {v, c -> def a = c.readVersion(); "\$1 $a";}]
}
```

And in info level logs:

```
Read version 0.2.15-SNAPSHOT from repository without using cache
Replacing pattern "(version:) 0.2.13" with "$1 0.2.15-SNAPSHOT" in README.md
```

Could you test this behavior? You would need to clone this repo, run `./gradlew install` and change import of `axion-release` from `plugins { }` notation to oldschool:

```
buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath group: 'pl.allegro.tech.build', name: 'axion-release-plugin', version: '1.3.1-development-SNAPSHOT'
    }
}

apply plugin: 'pl.allegro.tech.build.axion-release'
```

This way you will use local version instead of released one.

**Comment by imavroukakis** [comment] 2015-08-20 21:34
Excellent! I will be testing as soon as possible

**Comment by imavroukakis** [comment] 2015-08-20 22:07
aaaargh so.close.!

```
Read version 1.0.5-SNAPSHOT from repository without using cache <--- pre hook
Replacing pattern "module_version="1.0.5-SNAPSHOT"" with "module_version="1.0.5"" in src/main/scripts/upstart/cache-service.conf
Creating tag: cache-service-1.0.5
Replacing pattern "rpmRelease=16" with "rpmRelease=17" in gradle.properties
Read version 1.0.6-SNAPSHOT from repository without using cache <-- post hook
Replacing pattern "module_version="1.0.4"" with "module_version="1.0.6-SNAPSHOT"" in src/main/scripts/upstart/cache-service.conf
```
so the `pre` hook now works as I want it to. Now for this to be complete, the post hook needs to be able to replace the just released version (in this case, 1.0.5) with the new snapshot (1.0.6-SNAPSHOT), and we're in business!!

**Comment by adamdubiel** [comment] 2015-08-21 06:16
Ah, that's simple :) Just use `releaseVersion` from the context.

```
post 'fileUpdate', [file: 'README.md', pattern: {v, c -> /(version:) $c.releaseVersion/}, replacement: {v, c -> def a = c.readVersion(); "\$1 $a";}]
```

**Comment by imavroukakis** [comment] 2015-08-21 09:58
Like a boss! :bow: :bow: :bow: 

```
Executing task ':release' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Read version 1.0.9-SNAPSHOT from repository without using cache
Replacing pattern "module_version="1.0.9-SNAPSHOT"" with "module_version="1.0.9"" in src/main/scripts/upstart/cache-service.conf
Creating tag: cache-service-1.0.9
Replacing pattern "rpmRelease=19" with "rpmRelease=20" in gradle.properties
Read version 1.0.10-SNAPSHOT from repository without using cache
Replacing pattern "module_version="1.0.9"" with "module_version="1.0.10-SNAPSHOT"" in src/main/scripts/upstart/cache-service.conf
```

**Comment by adamdubiel** [comment] 2015-08-21 10:02
Great :) So now i have to check if anything needs cleanup and i will be ready to release next version, i will let you know. Maybe i will add some similar case as usage example.

**Comment by imavroukakis** [comment] 2015-08-21 10:06
Excellent. One last question. In a custom hook, can I do this: 
```
post { context ->
            def nextSnapshotVersion = context.position.readVersion();
            context.commit(['gradle.properties', "src/main/scripts/upstart/${rootProject.name}.conf"], "Next development iteration $nextSnapshotVersion")
        }
```

**Comment by imavroukakis** [comment] 2015-08-21 10:16
I'll answer my own question, no :)

**Comment by adamdubiel** [comment] 2015-08-21 11:08
I'm not sure what are you trying to achieve exactly, but you made a small mistake -> `readVersion()` is part of `context`, not `context.position`. Maybe it's doable after all?

**Comment by imavroukakis** [comment] 2015-08-21 11:22
I'm just trying to add the new development iteration version to the commit message. No biggie, can live without it if it doesn't give me the right thing :smile:

**Comment by adamdubiel** [comment] 2015-08-21 11:32
Hm, by the looks of it - it should work. Any specific problem?

**Comment by imavroukakis** [comment] 2015-08-21 13:55
THIS IS AWESOME :-D feel free to use my hooks example (change filenames to something else that's a bit more generic)

```
task doRpmBuildAndPublishAfterRelease(type: GradleBuild) {
    tasks = ['clean', 'buildRpm', 'publish']
}

scmVersion {

    nextVersion {
        suffix = 'devel'
        separator = '-'
    }

    tag {
        prefix = rootProject.name
        initialVersion = { config, position -> '1.0.0' }
    }

    hooks {
        pre 'fileUpdate', [file   : "src/main/scripts/upstart/${rootProject.name}.conf",
                           pattern: { v, p -> def snapshot = p.readVersion(); /module_version="$snapshot"/ }, replacement: { v, p -> "module_version=\"$v\"" }]
        post { context ->
            doRpmBuildAndPublishAfterRelease.execute()
        }
        post 'fileUpdate', [file   : 'gradle.properties',
                            pattern: { v, p -> /rpmRelease=$project.rpmRelease/ }, replacement: { v, p -> "rpmRelease=${project.rpmRelease.toInteger() + 1}" }]
        post { context ->
            context.commit(['gradle.properties'], "Advance RPM for next development iteration")
        }
        post 'fileUpdate', [file   : "src/main/scripts/upstart/${rootProject.name}.conf",
                            pattern: { v, p -> /module_version="$p.releaseVersion"/ }, replacement: { v, p ->
            def snapshot = p.readVersion(); "module_version=\"$snapshot\""
        }]
        post { context ->
            def nextSnapshot = context.readVersion();
            context.commit(['gradle.properties', "src/main/scripts/upstart/${rootProject.name}.conf"], "Next development iteration $nextSnapshot")
        }

        post 'push', {}
    }
}
project.version = scmVersion.version
```

**Comment by adamdubiel** [comment] 2015-08-21 14:03
Great, so we solved your issue entirely after nearly a month :) hope it was worth waiting for.

**Comment by imavroukakis** [comment] 2015-08-21 14:04
More than worth it, thank you for taking the time out of your schedule to help me accomplish this!

**Comment by adamdubiel** [comment] 2015-08-21 14:09
No problem, it will benefit all the users :) I will let you know when i will release it (this weekend probably).

**Comment by imavroukakis** [comment] 2015-08-24 09:58
Hey :-) any chance this will be released today?

**Comment by adamdubiel** [comment] 2015-08-24 11:37
Yes, sorry, i actually got blocked at trying to come up with some example setup that would be more generic than your usecase. I might just drop it for now and release it.

**Comment by adamdubiel** [comment] 2015-08-24 20:36
1.3.2 release, enjoy :)

**Closed by adamdubiel** 2015-08-24 20:36 UTC
