### ISSUE TITLE
Broken release on Maven Central

### ISSUE THREAD

**Issue by wiget** [allegro/axion-release-plugin#481] opened 2022-06-02 12:57 UTC
Jar for version 1.13.10 released to Maven Central is broken in some way. 
```
* What went wrong:
Could not apply requested plugin [id: 'pl.allegro.tech.build.axion-release', version: '1.13.10'] as it does not provide a plugin with id 'pl.allegro.tech.build.axion-release'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s).
> Plugin with id 'pl.allegro.tech.build.axion-release' not found.
```
Jar from Gradle Plugins works without problem.

https://plugins.gradle.org/m2/pl/allegro/tech/build/axion-release-plugin/1.13.10/axion-release-plugin-1.13.10.jar has md5 hash `fb245869dbbf1ebfd0eb25fe83c128fa`  
but https://repo1.maven.org/maven2/pl/allegro/tech/build/axion-release-plugin/1.13.10/axion-release-plugin-1.13.10.jar has md5 hash `d39481b8f5dc729250d2086ae313ba72`

**Comment by bgalek** [comment] 2022-06-02 17:13
@wiget thx for pointing out, gonna check it out as soon as possible!

**Comment by bgalek** [comment] 2022-06-02 17:51
I'm trying to figure out the problem, the faster way will be to release next version, @wiget will you check it?:)

**Comment by wiget** [comment] 2022-06-03 07:12
Sure, I can test. Just let me know version number.

**Comment by bgalek** [comment] 2022-06-03 14:29
@wiget i've released v1.13.11 - please check it out - this project is not ready to use anykind of gradle plugin snapshots ;(

**Comment by wiget** [comment] 2022-06-03 15:18
@bgalek comparing your last commit to Gradle [documentation](https://plugins.gradle.org/docs/publish-plugin#example) I think `gradlePlugin` should be defined outside `pluginsBundle`

Something like this
```
gradlePlugin {
    testSourceSets project.sourceSets.integration
    setAutomatedPublishing(false)
    plugins {
        release {
            id = 'pl.allegro.tech.build.axion-release'
            implementationClass = 'pl.allegro.tech.build.axion.release.ReleasePlugin'
        }
    }
}

pluginBundle {
    website = 'https://github.com/allegro/axion-release-plugin'
    vcsUrl = 'https://github.com/allegro/axion-release-plugin'
    description = 'Release and version management plugin.'
    tags = ['release', 'version']
    plugins {
        release {
            displayName = 'axion-release-plugin'
        }
    }
}

```

**Comment by bgalek** [comment] 2022-06-03 16:09
I've seen this, but during the local maven publication it looked like it didn't make any difference - if the latest version still has problems I'll try that. We need to move from build.gradle to kts so this kind of things will be type checked.

**Comment by bgalek** [comment] 2022-06-04 11:16
@wiget did you manage te test latest version? :)

**Comment by wiget** [comment] 2022-06-04 11:44
If you mean v1.13.11, then yes. I used this Gradle project to test it: https://github.com/wiget/axion-test

Running `./gradlew --info tasks` gives
```
> Configure project :app
Evaluating project ':app' using build file '/work/axion-test/app/build.gradle'.
Compiling build file '/work/axion-test/app/build.gradle' using SubsetScriptTransformer.
Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/pl/allegro/tech/build/axion-release/pl.allegro.tech.build.axion-release.gradle.plugin/1.13.11/pl.allegro.tech.build.axion-release.gradle.plugin-1.13.11.pom]

FAILURE: Build failed with an exception.

* Where:
Build file '/work/axion-test/app/build.gradle' line: 13

* What went wrong:
Plugin [id: 'pl.allegro.tech.build.axion-release', version: '1.13.11'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'pl.allegro.tech.build.axion-release:pl.allegro.tech.build.axion-release.gradle.plugin:1.13.11')
  Searched in the following repositories:
    MavenRepo

```
As you see metadata file for gradle plugin is missing on Maven Central.

**Comment by wiget** [comment] 2022-06-04 11:45
I used `gradle:7.4.2-jdk17-jammy` Docker image for tests.

**Comment by bgalek** [comment] 2022-06-05 16:55
@wiget I'll double checked jars published to maven local after moving `gradlePlugin` section it looks all right I hope it helps

**Comment by bgalek** [comment] 2022-06-05 17:00
released v1.13.12, 
I hope that in upcoming 1.14.0 with build-cache support and further kotlin compatibility improvements we will also move build.gradle to kts version and such dummy problems wont happen again ;)

**Comment by wiget** [comment] 2022-06-06 13:55
From my testing it look like `setAutomatedPublishing(false)` is causing the problem. 

Here is how local maven repository looks after `publishToMavenLocal`
```
└── pl
    └── allegro
        └── tech
            └── build
                └── axion-release-plugin
                    ├── 1.13.12
                    │   ├── axion-release-plugin-1.13.12.jar
                    │   ├── axion-release-plugin-1.13.12-javadoc.jar
                    │   ├── axion-release-plugin-1.13.12.module
                    │   ├── axion-release-plugin-1.13.12.pom
                    │   └── axion-release-plugin-1.13.12-sources.jar
                    └── maven-metadata-local.xml
```
and here with `setAutomatedPublishing(true)` (which is the default setting)
```
└── pl
    └── allegro
        └── tech
            └── build
                ├── axion-release
                │   └── pl.allegro.tech.build.axion-release.gradle.plugin
                │       ├── 1.13.12
                │       │   └── pl.allegro.tech.build.axion-release.gradle.plugin-1.13.12.pom
                │       └── maven-metadata-local.xml
                └── axion-release-plugin
                    ├── 1.13.12
                    │   ├── axion-release-plugin-1.13.12.jar
                    │   ├── axion-release-plugin-1.13.12-javadoc.jar
                    │   ├── axion-release-plugin-1.13.12.module
                    │   ├── axion-release-plugin-1.13.12.pom
                    │   └── axion-release-plugin-1.13.12-sources.jar
                    └── maven-metadata-local.xml
```
`pl.allegro.tech.build.axion-release.gradle.plugin-1.13.12.pom` it's crucial to resolve Gradle plugin id to artifact coordinates.

**Comment by bgalek** [comment] 2022-06-06 13:57
and with setAutomatedPublishing() maven publish fails saying that there are two artifacts that ale colliding ;/

**Comment by bgalek** [comment] 2022-06-06 14:06
@wiget https://github.com/allegro/axion-release-plugin/pull/486/files

**Comment by bgalek** [comment] 2022-06-06 14:39
@wiget https://github.com/allegro/axion-release-plugin/runs/6757276720?check_suite_focus=true I've managed to distinguish artifact from plugin from the actual jars (from components.java => artifact sourcesJar) so it should be ok now

**Comment by bgalek** [comment] 2022-06-06 15:03
@wiget it looks ok now https://github.com/allegro/axion-release-plugin/runs/6757628488?check_suite_focus=true

**Comment by bgalek** [comment] 2022-06-06 15:07
@wiget I've also updated badge ![Gradle Plugin Portal](https://img.shields.io/gradle-plugin-portal/v/pl.allegro.tech.build.axion-release) to see any differences with maven/gradle fast

**Comment by wiget** [comment] 2022-06-06 15:14
#487 should help for colliding artifacts

**Comment by bgalek** [comment] 2022-06-06 15:19
@wiget thx, this could also be the way to go - as for now, the issue is resolved with v1.13.13 right?

**Comment by wiget** [comment] 2022-06-06 15:21
Nope. 
```
Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/pl/allegro/tech/build/axion-release/pl.allegro.tech.build.axion-release.gradle.plugin/1.13.13/pl.allegro.tech.build.axion-release.gradle.plugin-1.13.13.pom]
```
plugin marker is missing.

**Comment by wiget** [comment] 2022-06-06 15:36
After successful release I will expect two directories here: https://repo1.maven.org/maven2/pl/allegro/tech/build/
- `axion-release` with plugin marker (pom)
- `axion-release-plugin` with all jars and pom

**Comment by wiget** [comment] 2022-06-06 15:48
Correct.

**Comment by bgalek** [comment] 2022-06-06 15:59
v1.13.14 released, it will take a while to sync maven central if you do not use sonatype as a taget

**Comment by bgalek** [comment] 2022-06-06 16:00
https://oss.sonatype.org/service/local/repositories/releases/content/pl/allegro/tech/build/axion-release/pl.allegro.tech.build.axion-release.gradle.plugin/1.13.14/
https://oss.sonatype.org/service/local/repositories/releases/content/pl/allegro/tech/build/axion-release-plugin/1.13.14/

**Comment by wiget** [comment] 2022-06-06 16:04
Works with following settings:
```
                maven {
                        url 'https://oss.sonatype.org/service/local/repositories/releases/content/'
                }
```
Will re-check against Maven Central in few hours.

**Closed** 2022-06-06 17:45 UTC
Labels: bug
